//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandsClothes.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_MaterialDetails2
    {
        public int Id { get; set; }
        public string MaterialName { get; set; }
        public string Type { get; set; }
        public string UnitName { get; set; }
        public decimal Price { get; set; }
        public int InPackAmount { get; set; }
        public string Description { get; set; }
        public string PhotoPath { get; set; }
        public int QtyInStock { get; set; }
        public int MinimalAmount { get; set; }
    }
}
