//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandsClothes.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_MaterialSuplier
    {
        public string MaterialType { get; set; }
        public string MaterialName { get; set; }
        public int MinimalAmount { get; set; }
        public int QtyInStock { get; set; }
        public string Supliers { get; set; }
        public string PhotoPath { get; set; }
    }
}
